# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73e24cbf5f3dd36348d15dbd3a837928bc7a5a275dde22a7734c29e4fdd40bf98f3c76d3156bfadce2d3d5b31cc0a43e40cb8fe82c9705cb05c19e423108abbc

test:
  secret_key_base: 3f1ed3ea6912e7d9df863de80bea964ec2f37b91d5a450199f152ba43ece8ea9d0fcdd1809e02c2f38c7a4eeefdd323abac514797ed3ce432ce7f9857753b2d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
